=== SrTeto/Ficha-Arbitral-XML-XSD/practicaActa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="acta" type="tipoActa">
        <!--KEY Y KEYREF-->
        <xs:key name="keyCodEquipo">
            <xs:selector xpath="clubes/club" />
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:key>
        <xs:keyref name="keyRefCod" refer="keyCodEquipo">
            <xs:selector xpath="equipos/equipo"></xs:selector>
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:keyref>
        <xs:keyref name="keyRefCodSus" refer="keyCodEquipo">
            <xs:selector xpath="sustituciones/sustitucion"></xs:selector>
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:keyref>
        <xs:keyref name="keyRefCodGoles" refer="keyCodEquipo">
            <xs:selector xpath="goles/gol/jugador"></xs:selector>
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:keyref>
        <xs:keyref name="keyRefCodTarjetas" refer="keyCodEquipo">
            <xs:selector xpath="tarjetas/tarjeta"></xs:selector>
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:keyref>
        <xs:keyref name="keyRefCodAmonestaciones" refer="keyCodEquipo">
            <xs:selector xpath="incidencias/amonestaciones/amonestacion"></xs:selector>
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:keyref>
        <xs:keyref name="keyRefCodExpulsiones" refer="keyCodEquipo">
            <xs:selector xpath="incidencias/expulsiones/expulsion"></xs:selector>
            <xs:field xpath="@codEquipo"></xs:field>
        </xs:keyref>
    </xs:element>
    <!--FIN SECCION KEY Y KEYREF-->
    <!--GRUPO-->
    <xs:group name="grupoIncidencias">
        <xs:sequence>
            <xs:element name="amonestaciones" type="tipoAmonestacion" />
            <xs:element name="expulsiones" type="expulsionesGeneral" />
            <xs:element name="otrasIncidencias" default="Ninguna" type="comentariosLargos" />
            <xs:element name="amonestacionTenicos" type="comentariosLargos" />
            <xs:element name="otrasIncidenciasTecnicas" type="comentariosLargos" />
            <xs:element name="publico" type="comentariosLargos" default="Normal" />
            <xs:element name="dotjei" type="comentariosLargos" default="Ninguna" />
            <xs:element name="ooaa" type="comentariosLargos" default="Ninguna" />
        </xs:sequence>
    </xs:group>
     <!--FIN SECCION GRUPO-->
    <!--TIPOSSIMPLES-->
    <xs:simpleType name="comentariosLargos">
        <xs:restriction base="xs:string">
            <xs:maxLength value="250"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoNum">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxInclusive value="30"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="formatoCod">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="puestoJugador">
        <xs:restriction base="xs:string">
            <xs:enumeration value="suplente" />
            <xs:enumeration value="titular" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoDni">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]{1}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoPasaporte">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}\d{6}[A-Z]{1}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nombreMax">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="arbitrPosicion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="principal" />
            <xs:enumeration value="asistente" />
            <xs:enumeration value="cuarto"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <!-- TIPOS COMPLEJOS-->
    <!-- CUERPO ACTA Y REFERENCIA MAYORES -->
    <xs:complexType name="tipoActa">
        <xs:sequence>
            <xs:element name="campeonato" type="xs:string" minOccurs="1" />
            <xs:element name="campo" type="xs:string" minOccurs="1" />
            <xs:element name="clubes" type="tipoClub" />
            <xs:element name="arbitros" type="tipoArbitro" />
            <xs:element name="equipos" type="tipoEquipo" />
            <xs:element name="resulFinal" type="tipoResultados" />
            <xs:element name="sustituciones" type="tipoSustitucion" />
            <xs:element name="goles" type="tipoPuntaje" />
            <xs:element name="tarjetas" type="tarjetas" />
            <xs:element name="incidencias" type="tipoIncidencias" />
        </xs:sequence>
        <xs:attribute name="fecha" use="required" type="xs:date" />
        <xs:attribute name="lugar" use="required" />
        <xs:attribute name="temporada" fixed="2023-2024" />
        <xs:attribute name="jornada" type="xs:integer" use="required" />
    </xs:complexType>
    <!-- SECCION CLUBES-->
    <xs:complexType name="tipoClubes">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="codEquipo" use="required" />
                <xs:attribute name="ciudad" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="tipoClub">
        <xs:sequence>
            <xs:element name="club" minOccurs="2" maxOccurs="2" type="tipoClubes"/>
        </xs:sequence>
    </xs:complexType>
    <!-- FIN SECCION CLUBES-->

    <!-- SECCION ARBITROS-->
    <xs:complexType name="tipoArbitros">
        <xs:sequence>
            <xs:element name="nombreApellidos" type="nombreMax" />
        </xs:sequence>
        <xs:attribute name="posicion" use="required" type="arbitrPosicion"/>
        <xs:attribute name="dni" type="tipoDni" use="optional" />
        <xs:attribute name="comite" use="required" />
        <xs:attribute name="pasaporte" type="tipoPasaporte" use="optional" />
    </xs:complexType>
    <xs:complexType name="tipoArbitro">
        <xs:sequence>
            <xs:element name="arbitro" maxOccurs="4" type="tipoArbitros" />
        </xs:sequence>
    </xs:complexType>
    <!-- FIN SECCION ARBITROS-->
    <!-- SECCION EQUIPOS-->
    <xs:complexType name="tipoJugador">
        <xs:sequence>
            <xs:element name="jugador" minOccurs="11" maxOccurs="unbounded" type="tipoJugadores" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoJugadores">
        <xs:all>
            <xs:element name="nombreApellido" type="nombreMax" />
            <xs:element name="goles" minOccurs="0" type="xs:string" />
        </xs:all>
        <xs:attribute name="dni" type="tipoDni" use="optional" />
        <xs:attribute name="num" type="tipoNum" use="required" />
        <xs:attribute name="tipoJugador" use="required" type="puestoJugador" />
        <xs:attribute name="pasaporte" type="tipoPasaporte" use="optional" />
    </xs:complexType>
    <xs:complexType name="tipoEntrenadorPrincipal">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="licencia" type="xs:integer" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tipoEntrenadorSecundario">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="licencia" type="xs:integer" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="tipoCuerpoTecnico">
        <xs:sequence>
            <xs:element name="entrenadorPrincipal" type="tipoEntrenadorPrincipal" minOccurs="1" maxOccurs="1"/>
            <xs:element name="entrenadorSecundario" type="tipoEntrenadorSecundario" minOccurs="0" maxOccurs="3"/>
            <xs:element name="delegadoCampo" minOccurs="1" maxOccurs="1" type="nombreMax" />
            <xs:element name="delegadoEquipo" minOccurs="0" maxOccurs="3" type="nombreMax" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipoEquipos">
        <xs:sequence>
            <xs:element name="cuerpoTecnico" type="tipoCuerpoTecnico"/>
            <xs:element name="jugadores" type="tipoJugador"/>
        </xs:sequence>
        <xs:attribute name="codEquipo" use="required" />
        <xs:attribute name="grupo" use="required" />
        <xs:attribute name="jugCapitan" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="tipoEquipo">
        <xs:sequence>
            <xs:element name="equipo" maxOccurs="2" minOccurs="2" type="tipoEquipos"/>
        </xs:sequence>
    </xs:complexType>
    <!-- FIN SECCION EQUIPOS-->

    <!--  SECCION RESULTADO FINAL-->
    <xs:complexType name="tipoTiempos">
        <xs:sequence>
            <xs:element name="equipo" minOccurs="2" maxOccurs="2"/>
        </xs:sequence>
        <xs:attribute name="horaInicio" use="required" type="xs:time" />
    </xs:complexType>
    <xs:complexType name="tipoTiempo">
        <xs:sequence>
            <xs:element name="tiempo" maxOccurs="unbounded" type="tipoTiempos"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipoResultados">
        <xs:sequence>
            <xs:element name="resultado" type="tipoTiempo"/>
        </xs:sequence>
    </xs:complexType>
    <!--  FIN SECCION RESULTADO FINAL -->
    <!--  SECCION SUSTITUCIONES-->
    <xs:complexType name="tipoEntra">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="num" type="tipoNum" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tipoSale">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="num" type="tipoNum" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tipoSustituciones">
        <xs:sequence>
            <xs:element name="entraBanco" type="tipoEntra">
            </xs:element>
            <xs:element name="saleCampo" type="tipoSale">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="codEquipo" use="required" />
        <xs:attribute name="min" use="required" />
    </xs:complexType>
    <xs:complexType name="tipoSustitucion">
        <xs:sequence>
            <xs:element name="sustitucion" maxOccurs="5" minOccurs="0" type="tipoSustituciones" />
        </xs:sequence>
    </xs:complexType>
    <!--  FIN SECCION SUSTITUCIONES-->
    <!--   SECCION GOLES-->

    <xs:complexType name="tipoGoles">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="codEquipo" use="required" />
                <xs:attribute name="num" type="xs:integer" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="tipoGol">
        <xs:sequence>
            <xs:element name="jugador" type="tipoGoles" />
        </xs:sequence>
        <xs:attribute name="min" use="required" />
    </xs:complexType>

    <xs:complexType name="tipoPuntaje">
        <xs:sequence>
            <xs:element name="gol" maxOccurs="unbounded" type="tipoGol" />
        </xs:sequence>
    </xs:complexType>
    <!--   FIN SECCION GOLES-->
    <!--    SECCION TARJETAS-->
    <xs:complexType name="tipoTarjetas">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="num" type="tipoNum" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tipoTarjeta">
        <xs:sequence>
            <xs:element name="jugador" type="tipoTarjetas" />
        </xs:sequence>
        <xs:attribute name="codEquipo" use="required" />
        <xs:attribute name="tarjetaTipo" use="required" />
        <xs:attribute name="min" use="required" />
    </xs:complexType>
    <xs:complexType name="tarjetas">
        <xs:sequence>
            <xs:element name="tarjeta" maxOccurs="unbounded" minOccurs="0" type="tipoTarjeta">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!--   FIN SECCION TARJETAS-->
    <!-- SECCION AMONESTACIONES-->
    <!--  SECCION EXPULSIONES-->
    <xs:complexType name="tipoExpulsiones">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="num" type="tipoNum" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tipoExpulsion">
        <xs:sequence>
            <xs:element name="jugador" type="tipoExpulsiones" />
            <xs:element name="motivo" type="comentariosLargos" />
        </xs:sequence>
        <xs:attribute name="codEquipo" use="required" />
        <xs:attribute name="min" use="required" />
    </xs:complexType>
    <xs:complexType name="expulsionesGeneral">
        <xs:sequence>
            <xs:element name="expulsion" type="tipoExpulsion" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <!--   FIN SECCION EXPULSIONES-->
    <xs:complexType name="tipoAmonestaciones">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="codEquipo" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tipoAmonestacion">
        <xs:sequence>
            <xs:element name="amonestacion" maxOccurs="unbounded" type="tipoAmonestaciones" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipoIncidencias">
        <xs:group ref="grupoIncidencias"/>
    </xs:complexType>
</xs:schema>

=== SrTeto/Ficha-Arbitral-XML-XSD/practicaActa.xml
<?xml version="1.0" encoding="UTF-8"?>
<acta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="practicaActa.xsd" fecha="2023-10-25" lugar="Alcala de Henares,Madrid" temporada="2023-2024" jornada="9">
    <!-- OJO CON ESTA FECHA QUE VA ESCRITA EN TEXTO EL MES-->
    <campeonato>Campeonato Nacional de Primera Division(Liga Regular-Ã™nico)</campeonato>
    <campo>Estadio Metropolitano Javier</campo>
    <clubes>
        <club codEquipo="CDL" ciudad="Alcala de Henares">Club Deportivo Lara</club>
        <!-- PREGUNTAR -->
        <club codEquipo="VFC" ciudad="Valencia">Valencia Futbol Club</club>
    </clubes>
    <arbitros>
        <arbitro posicion="principal" dni="75622849X" comite="CTA">
            <nombreApellidos>Pedro Lopez</nombreApellidos>
        </arbitro>
        <arbitro posicion="asistente" pasaporte="PHP908601J" comite="PGB">
            <nombreApellidos>Javier Navarro</nombreApellidos>
        </arbitro>
        <arbitro posicion="asistente" pasaporte="PHP908601J" comite="PGB">
            <nombreApellidos>Marek Nowak</nombreApellidos>
        </arbitro>
        <arbitro posicion="cuarto" pasaporte="FSF767012Y" comite="SFA">
            <nombreApellidos>Ewan MacLeod</nombreApellidos>
        </arbitro>
    </arbitros>
    <equipos>
        <!-- PRIMER EQUIPO-->
        <!-- La declaracion LOCAL O VISITANTE no fue requerida, la he implementado yo-->
        <equipo codEquipo="CDL" grupo="local" jugCapitan="2">
            <cuerpoTecnico>
                <entrenadorPrincipal licencia="3529">Cristobal Carrasco</entrenadorPrincipal>
                <entrenadorSecundario licencia="1128">Eren Jagger</entrenadorSecundario>
                <!-- NECESARIO Y OBLIGATORIO-->
                <delegadoCampo>Antonio  Velazquez</delegadoCampo>
                <!-- El delegado de equipo no siempre tiene que estar-->
                <!-- Delegado de equipo no es requerido, la he implementado yo-->
                <delegadoEquipo>Antonio  Velazquez</delegadoEquipo>
            </cuerpoTecnico>
            <jugadores>
                <jugador dni="54670551B" num="2" tipoJugador="titular">
                    <goles>1</goles>
                    <nombreApellido>Adalberto Carrasco</nombreApellido>
                </jugador>
                <jugador dni="32409819J" num="1" tipoJugador="titular">
                    <nombreApellido>Taliby Diakite</nombreApellido>
                </jugador>
                <jugador dni="18494019H" num="4" tipoJugador="titular">
                    <nombreApellido>FranciscoGarcia</nombreApellido>
                </jugador>
                <jugador dni="36641105N" num="5" tipoJugador="titular">
                    <nombreApellido>Arnau Gaixas Pont</nombreApellido>
                </jugador>
                <jugador dni="29003116R" num="7" tipoJugador="titular">
                    <nombreApellido>Eduardo Lorenz</nombreApellido>
                </jugador>
                <jugador pasaporte="ZIP939900X" num="8" tipoJugador="titular">
                    <nombreApellido>AHN JUNEHYUK</nombreApellido>
                </jugador>
                <jugador dni="09986091C" num="9" tipoJugador="titular">
                    <nombreApellido>Francisco  Jaramillo</nombreApellido>
                </jugador>
                <jugador pasaporte="DXZ315147F" num="10" tipoJugador="titular">
                    <nombreApellido>Arossio Dunkelheit</nombreApellido>
                    <goles>1</goles>
                </jugador>
                <jugador dni="31514772F" num="11" tipoJugador="titular">
                    <nombreApellido>Victor Gimenez</nombreApellido>
                </jugador>
                <jugador dni="83206993P" num="13" tipoJugador="titular">
                    <nombreApellido>Ricardo Garcia</nombreApellido>
                </jugador>
                <jugador dni="68798369X" num="15" tipoJugador="titular">
                    <nombreApellido>Rodrigo Cortez</nombreApellido>
                </jugador>
                <!-- JUGADORES SUSTITUCION-->
                <jugador dni="81610131J" num="23" tipoJugador="suplente">
                    <nombreApellido>Eladio Ramirez</nombreApellido>
                </jugador>
                <jugador dni="66325626C" num="6" tipoJugador="suplente">
                    <nombreApellido>Ramon Primo</nombreApellido>
                </jugador>
                <jugador dni="99623625E" num="14" tipoJugador="suplente">
                    <nombreApellido>Anyer Vargas</nombreApellido>
                </jugador>
                <jugador dni="28026804Q" num="29" tipoJugador="suplente">
                    <nombreApellido>Luis Moreno</nombreApellido>
                </jugador>
                <jugador pasaporte="HOP795930L" num="25" tipoJugador="suplente">
                    <nombreApellido>Nixon Velasquez</nombreApellido>
                </jugador>
            </jugadores>
        </equipo>
        <!--   SEGUNDO EQUIPO  -->
        <equipo codEquipo="VFC" grupo="Visitante" jugCapitan="3">
            <cuerpoTecnico>
                <entrenadorPrincipal licencia="8539">Salomon Rondon</entrenadorPrincipal>
                <entrenadorSecundario licencia="2295">Aitor Cringe</entrenadorSecundario>
                <!-- El delegado de equipo no siempre tiene que estar-->
                <delegadoCampo>Roberto Carlos</delegadoCampo>
            </cuerpoTecnico>
            <jugadores>
                <jugador dni="12345678A" num="16" tipoJugador="titular">
                    <nombreApellido>Javier Rodriguez</nombreApellido>
                </jugador>
                <jugador dni="98765432B" num="3" tipoJugador="titular">
                    <nombreApellido>Luis Sanchez</nombreApellido>
                </jugador>
                <jugador pasaporte="CZA302504Y" num="20" tipoJugador="titular">
                    <nombreApellido>Mario Gonzalez</nombreApellido>
                </jugador>
                <jugador dni="87654321D" num="12" tipoJugador="titular">
                    <nombreApellido>Pedro Martinez</nombreApellido>
                </jugador>
                <jugador pasaporte="QCA910653K" num="22" tipoJugador="titular">
                    <nombreApellido>Lautaro Rodriguez</nombreApellido>
                </jugador>
                <jugador dni="23456789F" num="17" tipoJugador="titular">
                    <nombreApellido>Juan Lopez</nombreApellido>
                </jugador>
                <jugador dni="87654321G" num="19" tipoJugador="titular">
                    <nombreApellido>Martin Fernandez</nombreApellido>
                </jugador>
                <jugador pasaporte="NVF837784P" num="21" tipoJugador="titular">
                    <nombreApellido>Carlos Ramirez</nombreApellido>
                </jugador>
                <jugador dni="76543210I" num="18" tipoJugador="titular">
                    <nombreApellido>Daniel Lopez</nombreApellido>
                </jugador>
                <jugador dni="65432109J" num="30" tipoJugador="titular">
                    <nombreApellido>Jose Hernandez</nombreApellido>
                </jugador>
                <!--jugadores
                suplentes -->
                <jugador dni="11223344K" num="24" tipoJugador="suplente">
                    <nombreApellido>Fernando Garcia</nombreApellido>
                </jugador>
                <jugador dni="99887766L" num="27" tipoJugador="suplente">
                    <nombreApellido>Eli Martinez</nombreApellido>
                </jugador>
                <jugador pasaporte="IGY961073A" num="26" tipoJugador="suplente">
                    <nombreApellido>Rafael Rodriguez</nombreApellido>
                </jugador>
                <jugador dni="44332211N" num="28" tipoJugador="suplente">
                    <nombreApellido>Miguel Lopez</nombreApellido>
                </jugador>
                <jugador pasaporte="XNZ719706Y" num="1" tipoJugador="suplente">
                    <nombreApellido>Anton Fernandez</nombreApellido>
                </jugador>
            </jugadores>
        </equipo>
    </equipos>
    <resulFinal>
        <resultado>
            <tiempo horaInicio="22:00:00">
                <equipo codEquipo="CDL" goles="2">DOS</equipo>
                <equipo codEquipo="VFC" goles="0">CERO</equipo>
            </tiempo>
            <tiempo horaInicio="23:00:00">
                <equipo codEquipo="CDL" goles="2">DOS</equipo>
                <equipo codEquipo="VFC" goles="0">CERO</equipo>
            </tiempo>
        </resultado>
    </resulFinal>
    <sustituciones>
        <sustitucion codEquipo="CDL" min="85'">
            <entraBanco num="2">Adalberto Carrasco</entraBanco>
            <saleCampo num="25">Nixon Velasquez</saleCampo>
        </sustitucion>
        <sustitucion codEquipo="VFC" min="80'">
            <entraBanco num="30">Jose Hernandez</entraBanco>
            <saleCampo num="28">Miguel Lopez</saleCampo>
        </sustitucion>
        <sustitucion codEquipo="VFC" min="92'">
            <entraBanco num="22">Lautaro Rodriguez</entraBanco>
            <saleCampo num="1">Anton Fernandez</saleCampo>
        </sustitucion>
        <sustitucion codEquipo="VFC" min="89'">
            <entraBanco num="21">Carlos Ramirez</entraBanco>
            <saleCampo num="26">Rafael Rodriguez</saleCampo>
        </sustitucion>
    </sustituciones>
    <goles>
        <gol min="10'">
            <jugador codEquipo="CDL" num="2">Adalberto Carrasco</jugador>
        </gol>
        <gol min="44">
            <jugador codEquipo="CDL" num="10">Arossio Dunkelheit</jugador>
        </gol>
    </goles>
    <tarjetas>
        <tarjeta codEquipo="CDL" tarjetaTipo="amarilla" min="37'">
            <jugador num="2">Adalberto Carrasco</jugador>
